name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Set up Cygwin (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install cygwin --params "/InstallDir:C:\\cygwin" --yes
          choco install cyg-get --yes
          cyg-get make gcc-core gcc-g++
        shell: cmd

      - name: Configure project
        run: |
          cmake -S . -B build -G "Unix Makefiles"
        shell: bash

      - name: Build project
        run: |
          cmake --build build
        shell: bash

      - name: Package binaries
        run: |
          cd build
          zip -r project-${{ matrix.os }}.zip .
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-binaries
          path: build/project-${{ matrix.os }}.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts
          asset_name: binaries-${{ runner.os }}.zip
          asset_content_type: application/zip

      - name: Upload source code
        run: zip -r source-code.zip .
      - name: Upload source code to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: source-code.zip
          asset_name: source-code.zip
          asset_content_type: application/zip
